### ISSUE TITLE
Disable popup interruptions

### ISSUE THREAD

**Issue by haakonstorm** [zokugun/vscode-explicit-folding#22]
<img width="462" alt="Screenshot of Code (27-05-2020, 18-21-40)" src="https://user-images.githubusercontent.com/193781/83046208-fe21bc00-a046-11ea-8b86-008b578313de.png">

How to disable this popup?

**Comment by waldyrious** [comment]
FWIW, I follow this repository and because of that I am aware that the reason the extension is updated so often is because the author is actually very responsive and quick to fix any reported issues, so I just wanted to express my admiration and gratitude for such dedicated maintenance of the extension! ❤️ 

That said, I do agree that it would probably be better to keep those notifications reserved for (at least) minor version upgrades. Having one pop up at every patch release is a little disconcerting because VSCode doesn't usually show such popups unless something went wrong or there's an action the user needs to take.

**Comment by daiyam** [comment]
On the next update, I will add an option to control those notifications. Its possible values are going to be: `none`, `major`, `minor` and `patch`. By default, `minor` it will be. :smiley:

**Comment by haakonstorm** [comment]
`zokugun/vscode-explicit-folding` project is amazing. 
I use it every day and 👀 and ⭐ the repo.
This way I am notified of new releases for my dependencies in a single place.

But, now in 2020 we have information overload. Constant interruption.
This is not beneficial for development. 
Developer of this plugin I think want to help other developer.
Standard now in 2020 more and more is *opt-in* everywhere: newsletter, signing up for new service, notification. 
`Apple` and other big players aware; built functionality to limit interruptions. 
My feedback is rooted in our common goal of helping other developer. 
In feedback: I try to be short, to the point. 
In gratitude: I show my gratitude by using repo, and watching and starring repo. Increasing developer stats on Github. Or, by one time donation, once a year, or via the Patreon system.
Ultimately, when many people do this, developer rise, more people aware, ultimately, developer can afford more time on helping other developer with amazing continous development of repo.
Thank you. Sorry this was long.

**Comment by daiyam** [comment]
@haakonstorm I'm going to update the extension to fix the issue #24 
If you add `"explicitFolding.notification": "none"`, the updated extension won't show anymore notifications.
